### ISSUE TITLE
build process:  Cannot find module 'lodash.kebabcase'

### ISSUE THREAD

**Issue by laurentpayot** [quasarframework/quasar#2404]
### Software version

Quasar: 0.17.7
OS: Ubuntu 18.04 LTS
Node: 10.0.0
NPM: 6.3.0

### What did you get as the error?
```
> node build/script.build.js


 💥 Cleaned build artifacts.

 📦 Building Quasar v0.17.7... [multi-threaded]

[js]   dist/babel-transforms/imports.ios.js        8.33kb
[js]   dist/babel-transforms/imports.mat.js        8.33kb
[js]   dist/umd/quasar.ie.polyfills.umd.min.js     6.91kb (gzipped:   2.67kb)
[js]   dist/quasar.ie.polyfills.js                 8.87kb (gzipped:   3.07kb)
[css]  dist/quasar.ios.styl                       98.48kb
[css]  dist/quasar.mat.styl                       98.94kb
[css]  dist/umd/quasar.addon.css                  68.36kb (gzipped:   5.76kb)
[css]  dist/umd/quasar.ios.css                   136.38kb (gzipped:  20.26kb)
[css]  dist/umd/quasar.mat.css                   138.62kb (gzipped:  20.48kb)
[css]  dist/umd/quasar.addon.min.css              45.31kb (gzipped:   5.11kb)
[css]  dist/umd/quasar.ios.min.css                94.04kb (gzipped:  17.89kb)
[css]  dist/umd/quasar.mat.min.css                94.99kb (gzipped:  18.04kb)
[js]   dist/umd/quasar.mat.umd.js                566.84kb
[js]   dist/umd/quasar.ios.umd.js                559.74kb
[js]   dist/quasar.ios.esm.js                    304.00kb (gzipped:  78.02kb)
[js]   dist/quasar.mat.esm.js                    307.21kb (gzipped:  78.99kb)
[js]   dist/umd/quasar.mat.umd.min.js            296.09kb (gzipped:  77.18kb)
[js]   dist/umd/quasar.ios.umd.min.js            293.09kb (gzipped:  76.18kb)
(node:23573) UnhandledPromiseRejectionWarning: Error: Cannot find module 'lodash.kebabcase'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/laurent/projects/myproject/quasar/.quasar/build/build.helpers.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
(node:23573) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23573) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with anon-zero exit code.
```

### What were you expecting?
Completed build.

### What steps did you take, to get the error?
```
npm run build
```
It was working with Quasar 0.16.x.
