### ISSUE TITLE
test component with infinite-scroll always show error

### ISSUE THREAD

**Issue by goforu** [quasarframework/quasar#15726]
### What happened?

when upgrade from quasar v2.10.1 to 2.11.0，component with InfiniteScroll unit testing fails. 

`e[t] is not a function
TypeError: e[t] is not a function
    at /Users/joey/Documents/codespace/Repo/lab/hsql/node_modules/quasar/dist/quasar.esm.prod.js:6:275614
    at Array.forEach (<anonymous>)
    at S (/Users/joey/Documents/codespace/Repo/lab/hsql/node_modules/quasar/dist/quasar.esm.prod.js:6:275598)
    at /Users/joey/Documents/codespace/Repo/lab/hsql/node_modules/quasar/dist/quasar.esm.prod.js:6:275688
    at callWithErrorHandling (/Users/joey/Documents/codespace/Repo/lab/hsql/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at callWithAsyncErrorHandling (/Users/joey/Documents/codespace/Repo/lab/hsql/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:166:21)
    at Array.job (/Users/joey/Documents/codespace/Repo/lab/hsql/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1770:17)
    at flushPreFlushCbs (/Users/joey/Documents/codespace/Repo/lab/hsql/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:325:45)
    at flushJobs (/Users/joey/Documents/codespace/Repo/lab/hsql/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:365:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

### What did you expect to happen?

no error

### Reproduction URL

no url

### How to reproduce?

jest unit test Component with InfiniteScroll

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Quasar info output

```Shell
Operating System - Darwin(21.6.0) - darwin/x64
NodeJs - 16.13.2

Global packages
  NPM - 8.1.2
  yarn - 1.22.11
  @quasar/cli - 1.0.5
  @quasar/icongenie - 2.4.0
  cordova - Not installed

Important local packages
  quasar - 2.11.10 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.3.3 -- Quasar Framework local CLI
  @quasar/extras - 1.16.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - 1.1.0 -- Official ESLint plugin for Quasar
  vue - 3.2.31 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  vuex - 4.1.0 -- state management for Vue.js
  electron - 21.4.3 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 15.5.2 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - 23.6.0 -- A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box
  @babel/core - 7.21.4 -- Babel compiler core.
  webpack - 5.77.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.7.4 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 6.5.4 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - 3.9.0 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/cli - Not installed
  @capacitor/android - 3.9.0 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/ios - 3.9.0 -- Capacitor: Cross-platform apps with JavaScript and the web

Quasar App Extensions
  @quasar/quasar-app-extension-testing - 2.1.0 -- A Quasar App Extension for managing Test Harnesses
  @quasar/quasar-app-extension-testing-e2e-cypress - 1.0.0-beta.13 -- A Quasar App Extension for Cypress e2e
  @quasar/quasar-app-extension-testing-unit-jest - 3.0.0-beta.5 -- A Quasar App Extension for running Jest tests

Networking
  Host - Joeys-MacBook-Pro.local
  en0 - 192.168.102.4
  feth3433 - 192.168.192.156
```

**Comment by goforu** [comment]
Anyone help?

**Comment by rstoenescu** [comment]
The latest is now 2.11.10. Try with that.
Regardless, a reproduction would help us help you, otherwise there isn't much we can do with the error log above.

**Comment by rstoenescu** [comment]
Closed because no reproduction repo was supplied.
