### ISSUE TITLE
analyze: true broken in @quasar/app-vite 2.5.x

### ISSUE THREAD

**Issue by lajuffermans** [quasarframework/quasar#18263]
### What happened?

I got the following error when running `quasar build` with `analyze: true`

```
TypeError: rollupPluginVisualizer.visualizer is not a function
```

I have a feeling it's due to rollup -> rolldown changes in the @quasar/app-vite project. I got it since I update from 2.4.x to 2.5.x

### What did you expect to happen?

Build the project, show the report.

### Reproduction URL

https://codepen.io/lajuffermans/pen/ZYpaYaX

Ignore that ^

### How to reproduce?

1. Upgrade your quasar project to use @quasar/app-vite 2.5.3 (or use a fresh project)
2. Modify the quasar config file (`analyze: true`)
3. Run `quasar build`

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Quasar info output

```Shell
Operating System - Darwin(25.2.0) - darwin/arm64
NodeJs - 22.22.1

Global packages
  NPM - 10.9.4
  yarn - Not installed
  pnpm - Not installed
  bun - Not installed
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.18.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 2.5.2 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.17.0 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.5.30 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 5.0.4
  pinia - 3.0.4 -- Intuitive, type safe and flexible Store for Vue
  vite - 8.0.2 -- Native-ESM powered web dev build tool
  vite-plugin-checker - Not installed
  eslint - 9.39.4 -- An AST-based pattern checker for JavaScript.
  esbuild - 0.27.4 -- An extremely fast JavaScript and CSS bundler and minifier.
  typescript - 5.9.3 -- TypeScript is a language for application scale JavaScript development
  workbox-build - Not installed
  register-service-worker - Not installed
  electron - Not installed
  @electron/packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
```

### Relevant log output

```Shell
TypeError: rollupPluginVisualizer.visualizer is not a function
```

**Comment by yusufkandemir** [comment]
Hi 👋 Thanks for reporting. The fix will be included in the next release.
