### ISSUE TITLE
Meta doesn't work with SSR+PWA & quasar@1.7.4 

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar#6140]
**Describe the bug**
``` 
app:browser Opening default browser at http://localhost:8081/ +47s

/en -> error during render
TypeError: App.$getMetaHTML is not a function
```

**To Reproduce**
1. upgrade a long-lived SSR project to `quasar@1.7.4`
2. use `meta () {}` in your layout file
3. get a 500 response

**Expected behavior**
no 500

**Resolution**
Pin quasar to 1.7.3

**Comment by rstoenescu** [comment]
Nothing has changed to quasar regarding Meta from 1.7.3 to 1.7.4.
More important than that is the q/app version that you are using.

**Comment by nothingismagick** [comment]
using @quasar/app@1.5.2

**Comment by rstoenescu** [comment]
Quasar docs are also using the Meta plugin, so it's most likely not a bug in Quasar...

**Comment by rstoenescu** [comment]
Can you try to put a minimal reproduction repo (or better, [codesandbox](https://codesandbox.quasar.dev)) to highlight the issue, pls?

**Comment by nothingismagick** [comment]
Now I can't replicate anymore. I removed the ssr-mode, readded it, updated to 1.7.4, reran yarn and now the issue has disappeared. I am wondering if this has to do with general npmjs distribution flakiness. I had massive problems with electron yesterday... Anyway, sorry for the noise.

**Comment by rstoenescu** [comment]
No problem. Just glad it's no bug :)
