### PR TITLE
fix/feat(ui): Fix and improve Dialog plugin types (fix: #14766)

### LINKED ISSUE #14766: Invalid TypeScript types for QDialogOption's prompt and options
### What happened?

When upgrading quasar to v2.10.1 and then run vue-tsc I get following errors:

```
> vue-tsc --noEmit && vite build

node_modules/.pnpm/quasar@2.10.1/node_modules/quasar/dist/types/index.d.ts:13315:5 - error TS2374: Duplicate index signature for type 'string'.

13315     [QInputProps: string]: any;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/quasar@2.10.1/node_modules/quasar/dist/types/index.d.ts:13319:5 - error TS2374: Duplicate index signature for type 'string'.

13319     [nativeAttributes: string]: any;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/quasar@2.10.1/node_modules/quasar/dist/types/index.d.ts:13347:5 - error TS2374: Duplicate index signature for type 'string'.

13347     [QOptionGroupProps: string]: any;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/quasar@2.10.1/node_modules/quasar/dist/types/index.d.ts:13351:5 - error TS2374: Duplicate index signature for type 'string'.

13351     [nativeAttributes: string]: any;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors in the same file, starting at: node_modules/.pnpm/quasar@2.10.1/node_modules/quasar/dist/types/index.d.ts:13315

 ELIFECYCLE  Command failed with exit code 2.
```

### What did you expect to happen?

No errors

### Reproduction URL

Will provide if needed later on

### How to reproduce?

Install quasar
Look into `node_modules/quasar/dist/types/index.d.ts` lines 13315, 13319, 13347 and 13351

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar), TypeScript Support

### Platforms/Browsers

_No response_

### Quasar info output

```Shell
I'm using vite plugin, so I don't have `quasar info`
```

### Relevant log output

_No response_

### Additional context

image

image

### PR DESCRIPTION
**Pull request by yusufkandemir**
**What kind of change does this PR introduce?**

- Bugfix
- Feature

**Does this PR introduce a breaking change?**

- No

**The PR fulfills these requirements:**

- It's submitted to the `dev` branch (or `v[X]` branch)
- When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)

**Other information:**
Fixes #14766

### CODE REVIEW

**Comment by IlCallo** [comment]
LGTM, merging
