### ISSUE TITLE
Quasar build failed with an 'undefined' error, but succeeded with -d option

### ISSUE THREAD

**Issue by ParticleG** [quasarframework/quasar#10470]
**Describe the bug**
`quasar build` command only success with `-d` option. Without `-d` it would raise an "undefined" error.

**To Reproduce**
1. Clone the project : https://github.com/ParticleG/Lets-Team-Up
2. Run following commands
```bash
npm install
quasar build
```
3. Then you would see the error:
```
Build mode........ spa
 Pkg quasar........ v2.0.4
 Pkg @quasar/app... v3.1.0
 Pkg webpack....... v5
 Debugging......... no
 Publishing........ no

 Configured browser support (>= 88.74% of global marketshare):
 · Chrome for Android >= 92
 · Firefox for Android >= 90
 · Android >= 92
 · Chrome >= 83
 · Edge >= 89
 · Firefox >= 82
 · iOS >= 11.0-11.2
 · Opera >= 74
 · Safari >= 11.1

 App • Chaining "UI" Webpack config
 App • Cleaned build artifact: "{YOUR_FOLDER}\lets_team_up\dist\spa"
 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with errors • 15658ms

 App •  ERROR  •  UI  

undefined


 App •  COMPILATION FAILED  • Please check the log above for details.

```
4.Now try to build in debug mode:
Run following commands
```bash
quasar build -d
```
5.It should now build without any error

**Expected behavior**
Whether `-d` option is given or not, the project should be built with no errors

**Screenshots**
Try building release:
![try building release](https://user-images.githubusercontent.com/38580644/130746408-dff29059-f94c-4e29-a4a2-cb6cf7042cc0.png)

Try building debug:
![image](https://user-images.githubusercontent.com/38580644/130746678-1eb2bea7-9e1a-42f8-bb2b-121c81c1b29f.png)

**Platform (please complete the following information):**
Quasar Version:  2.0.0
@quasar/app Version: 3.0.0

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 11 Pro (21H2, 22000.160)
Node:  14.17.4
NPM: 6.14.14
Yarn: Not installed
Browsers: Microsoft Edge (92.0.902.78)
iOS: Haven't tested
Android: Haven't tested
Electron: Haven't tested

**Comment by faxinwang** [comment]
I have a similer pro
blem. When I upgrade quasar from 2.0.4 to 2.2.2 and @quasar/app from 3.1.0 to 3.1.7 . I got :
![image](https://user-images.githubusercontent.com/30144486/139648727-7db63c78-4fb3-4c78-a863-40b86cd54348.png)

Then I rollback to the original versions, the problem still exists. Since I have not put yarn.lock input git repository, now I can not go back and can not get the project running up. I really don't know where the problem is.

**Comment by rstoenescu** [comment]
Hi,

Thank you both for reporting.
This is a two-parter: first one I enhanced the error reporting; then by seeing the actual problem in your cases I could take care of your usage in index.template.html (the productName and productDescription needed to be escaped before injecting into the html file).

Improvement + Fix will be available in "@quasar/app" v3.1.11

**Comment by faxinwang** [comment]
With the new error reporting, I still can't figure out what it is that caused this problem.

![image](https://user-images.githubusercontent.com/30144486/143365298-5ba8e2fa-201b-4c85-8a87-c437901ea74b.png)

do you have some insight on it?

Note, there is no difference when I comment the productName and productDescription in the `index.template.html` file.

**Comment by sumon-devxhub** [comment]
I'm using 
- node -v = 18.12.0,
- npm -v =8.19.2,
- yarn -v=1.22.19

![image](https://user-images.githubusercontent.com/96725627/218316763-ba30f33d-5739-42d6-89cd-30711f39529f.png)

And also follow above solution but this problem is not solve yet

@rstoenescu  please check.

**Comment by yusufkandemir** [comment]
@SuMon-DevXHub you didn't provide any useful information and it's been so long since I last see this error, but I am going to take a guess and say that you were migrating from q/app v1 to v2 and skipped a step.
https://v1.quasar.dev/quasar-cli/app-upgrade-guide#required-steps:
> Edit your /src/index.template.html file:
  search for “htmlWebpackPlugin.options.” and replace with “” (empty string)

If not, then provide some context. What is the output of `quasar info`, what was the last thing you did before the error occurred, etc.?
