### ISSUE TITLE
Invalid TypeScript types for QDialogOption's prompt and options

### ISSUE THREAD

**Issue by Shinigami92** [quasarframework/quasar#14766]
### What happened?

When upgrading quasar to v2.10.1 and then run vue-tsc I get following errors:

```
> vue-tsc --noEmit && vite build

node_modules/.pnpm/quasar@2.10.1/node_modules/quasar/dist/types/index.d.ts:13315:5 - error TS2374: Duplicate index signature for type 'string'.

13315     [QInputProps: string]: any;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/quasar@2.10.1/node_modules/quasar/dist/types/index.d.ts:13319:5 - error TS2374: Duplicate index signature for type 'string'.

13319     [nativeAttributes: string]: any;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/quasar@2.10.1/node_modules/quasar/dist/types/index.d.ts:13347:5 - error TS2374: Duplicate index signature for type 'string'.

13347     [QOptionGroupProps: string]: any;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/.pnpm/quasar@2.10.1/node_modules/quasar/dist/types/index.d.ts:13351:5 - error TS2374: Duplicate index signature for type 'string'.

13351     [nativeAttributes: string]: any;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors in the same file, starting at: node_modules/.pnpm/quasar@2.10.1/node_modules/quasar/dist/types/index.d.ts:13315

 ELIFECYCLE  Command failed with exit code 2.
```

### What did you expect to happen?

No errors

### Reproduction URL

Will provide if needed later on

### How to reproduce?

Install quasar
Look into `node_modules/quasar/dist/types/index.d.ts` lines 13315, 13319, 13347 and 13351

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar), TypeScript Support

### Quasar info output

```Shell
I'm using vite plugin, so I don't have `quasar info`
```

### Additional context

<img width="600" alt="image" src="https://user-images.githubusercontent.com/7195563/199181117-2e777e69-e479-4706-a90d-b2e72b6ccd1a.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/7195563/199181068-7e615ee0-1657-4b3b-b57b-f609f9fdcf18.png">

**Comment by Shinigami92** [comment]
Pinning quasar to `2.10.0` fixes this for now!
So this came in in the last bug-fix version

**Comment by yusufkandemir** [comment]
Caused by https://github.com/quasarframework/quasar/commit/fb9bdaf77af78f4e01641a3709a4ee432a833927#diff-9b1d6b642d3c0d9d26b5eb502da68e9e755e4026e27283a6a496b3ead2e9277f
